from enum import Enum


class ScenarioEvent(Enum):
    ON_USER_MESSAGE = "ON_USER_MESSAGE"
    ON_USER_MESSAGE_TO_ADVISOR = "ON_USER_MESSAGE_TO_ADVISOR"
    ON_ADVISOR_MESSAGE = "ON_ADVISOR_MESSAGE"
    ON_AGENT_MESSAGE = "ON_AGENT_MESSAGE"
    ON_STAGE_CHANGE = "ON_STAGE_CHANGE"
